#!/usr/bin/env python3
"""Generate per-locale .strings files from translations data.

Uses classic en.lproj/Localizable.strings instead of Localizable.xcstrings so Xcode
does not merge auto-extracted junk keys (which caused extreme memory use on Run).
"""

from pathlib import Path

LOCALES = ["es", "ca", "fr", "nl", "de", "zh-Hans", "ja", "it", "pt", "ru"]
ALL_LOCALES = ["en"] + LOCALES

ROOT = Path(__file__).resolve().parent.parent
COOKGPT_DIR = ROOT / "src" / "CookGPT"

# Legacy catalogs — remove if present so Xcode stops processing them.
LEGACY_CATALOGS = (
    COOKGPT_DIR / "Localizable.xcstrings",
    COOKGPT_DIR / "InfoPlist.xcstrings",
)


def load_translations() -> dict[str, dict[str, str]]:
    from translation_data import TRANSLATIONS

    return TRANSLATIONS


def escape_strings_value(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def write_strings_file(path: Path, entries: dict[str, str]) -> None:
    lines = [
        "/* Generated by scripts/generate_localizations.py — do not edit by hand. */",
        "",
    ]
    for key in sorted(entries):
        if not key.strip():
            continue
        lines.append(f'"{escape_strings_value(key)}" = "{escape_strings_value(entries[key])}";')
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def localized_entries(
    translations: dict[str, dict[str, str]], locale: str
) -> dict[str, str]:
    entries: dict[str, str] = {}
    for english, locale_values in translations.items():
        if not english.strip():
            continue
        if locale == "en":
            entries[english] = locale_values.get("en", english)
        else:
            entries[english] = locale_values.get(locale, locale_values.get("en", english))
    return entries


def remove_legacy_catalogs() -> None:
    for path in LEGACY_CATALOGS:
        if path.exists():
            path.unlink()
            print(f"Removed legacy catalog {path.name}")


def main() -> None:
    translations = load_translations()
    remove_legacy_catalogs()

    for locale in ALL_LOCALES:
        lproj = COOKGPT_DIR / f"{locale}.lproj"
        write_strings_file(
            lproj / "Localizable.strings",
            localized_entries(translations, locale),
        )
        write_strings_file(
            lproj / "InfoPlist.strings",
            {
                "CFBundleDisplayName": "CookGPT",
                "CFBundleName": "CookGPT",
            },
        )

    print(
        f"Wrote {len(translations)} strings × {len(ALL_LOCALES)} locales "
        f"to {COOKGPT_DIR}/*.lproj/"
    )


if __name__ == "__main__":
    main()
